# 默认配置（共享）
spring:
  profiles:
    active: ${profile.active}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sprint_db
    username: root
    password: ADMIN123
    type: com.alibaba.druid.pool.DruidDataSource

---
# 开发环境
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8081

---
# 测试环境
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8082

---
# 生产环境
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 80